version: "2.1"
services:
  database:
    privileged: true
    build:
      context: database/.
      args:
        SAM_DEFAULT_ADMIN_USER_EMAIL: ${SAM_DEFAULT_ADMIN_USER_EMAIL}
        SAM_DEFAULT_ADMIN_USER_PASSWORD: ${SAM_DEFAULT_ADMIN_USER_PASSWORD}
        SAM_DEFAULT_ADMIN_USER_NAME: ${SAM_DEFAULT_ADMIN_USER_NAME}
        SAM_DEFAULT_ADMIN_USER_SURNAME: ${SAM_DEFAULT_ADMIN_USER_SURNAME}
    restart: on-failure
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=${DATABASE_PASSWORD}
      - DBNAME=${DATABASE_NAME}
      - PERSISTENT_HOME=false
    ports:
      - "50000:50000"
    volumes:
      - C:\docker-volumes\soccer-activities-management-database:/database
    healthcheck:
      test: source /home/db2inst1/sqllib/db2profile && cd /home/db2inst1/sqllib/bin/ && ./db2 connect to sam && ./db2 ping sam || exit 1
      timeout: 20s
      retries: 10
  web-api:
    build:
      context: .
      dockerfile: web-api/Dockerfile
      args:
        JWT_PUBLIC_KEY_SOURCE_PATH: ${JWT_PUBLIC_KEY_SOURCE_PATH}
        JWT_PRIVATE_KEY_SOURCE_PATH: ${JWT_PRIVATE_KEY_SOURCE_PATH}
        JWT_PUBLIC_KEY_DESTINATION_PATH: ${JWT_PUBLIC_KEY_DESTINATION_PATH}
        JWT_PRIVATE_KEY_DESTINATION_PATH: ${JWT_PRIVATE_KEY_DESTINATION_PATH}
    restart: on-failure
    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - CORS_ALLOWED_ORIGINS=${FRONTEND_URL}:${FRONTEND_PORT}
      - CORS_ALLOWED_METHODS=${CORS_ALLOWED_METHODS}
      - JWT_PUBLIC_KEY_DESTINATION_PATH=${JWT_PUBLIC_KEY_DESTINATION_PATH}
      - JWT_PRIVATE_KEY_DESTINATION_PATH=${JWT_PRIVATE_KEY_DESTINATION_PATH}
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
  frontend:
    build:
      context: frontend/.
    restart: on-failure
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - web-api