version: "2.1"
services:
  database:
    privileged: true
    build: database/.
    restart: on-failure
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=12345678
      - DBNAME=sam
      - PERSISTENT_HOME=false
    volumes:
      - C:\docker-volumes\soccer-activities-management-database:/database
    healthcheck:
      test: source /home/db2inst1/sqllib/db2profile && cd /home/db2inst1/sqllib/bin/ && ./db2 connect to sam && ./db2 ping sam || exit 1
      timeout: 20s
      retries: 10
  web-api:
    build: web-api/.
    restart: on-failure
    ports:
      - "8080:8080"
    links:
      - database
    depends_on:
      database:
        condition: service_healthy