INSERT INTO SAM.USER (Id, Email, Password, Name, Surname, Role, Active)
VALUES (1, '$SAM_DEFAULT_ADMIN_USER_EMAIL', '$SAM_DEFAULT_ADMIN_USER_PASSWORD', '$SAM_DEFAULT_ADMIN_USER_NAME', '$SAM_DEFAULT_ADMIN_USER_SURNAME', 'Admin', 'Y');

INSERT INTO SAM.Admin_User (Id)
VALUES (1);